### ISSUE TITLE
Drag to bottom of list doesn’t work

### ISSUE THREAD

**Issue by heymartinadams** [zheksoon/snapdrag#2]
When you drag it to the bottom of a list, the `onDragOut` function is triggered instead of the `onDrop` function.
![CleanShot 2024-11-06 at 12 29 50](https://github.com/user-attachments/assets/b0c7c5ae-4758-4411-b8f3-4e57a6e1e096)

Btw, really appreciate your work! Planning on integrating it into [OneTask](https://onetask.me) for a much more performant drag-and-drop experience over Framer Motion.

**Comment by zheksoon** [comment]
Hi, thanks for your feedback! Could you please provide the code or reproduceable example for this? Maybe it's about the missing placeholder on the bottom of the list - the `onDrop` should trigger on it instead of the handler on the list element itself.

**Comment by heymartinadams** [comment]
Hi @zheksoon, sorry the late reply. I ended up reverting back to a previous D&D library I used, so unable to provide you with the code or a reproducible example. Thanks for getting back anyhow!
